### ISSUE TITLE
0.47.4 Map Editor - CTRL+scroll change to Bridge class

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1762]
When doing 'CTRL+Scroll' over the bridge icon to change the Bridge Class value, if you've used 'ALT+click' to select an existing bridge, you lose the 'Exits' value for the existing bridge.

**Comment by Windchild292** [comment]
I think this one might be fixed, but I'm not certain.

**Comment by SimonLandmine** [comment]
Woohoo! :-) Faster than a speeding Locust!

**Comment by Windchild292** [comment]
Yep, this one is fixed.

**Comment by Windchild292** [comment]
This isn't working?

**Comment by SimonLandmine** [comment]
Sorry, @Windchild292 - still showing up in 47.5.
'CTRL+Scroll' over the bridge icon in the visual terrain picker causes the 'Exits' value to disappear from the hex info field.

**Comment by SimonLandmine** [comment]
> This isn't working?

Afraid it doesn't seem to be. 'Exits' value still disappearing.

**Comment by Windchild292** [comment]
I think this might be a recursion from my other exit changes.

**Comment by SimonLandmine** [comment]
Ah! I was going to suggest another Exits change as a UI improvement ... sorry!

**Comment by Windchild292** [comment]
Feel free to suggest 😄
