### ISSUE TITLE
MegaMek Scenarios with a bot start inconsistently

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#2776]
Win10, from Eclipse, current dev version.

Scenarios with a bot player (in other words: not only Me & Other Human) hang in about 80% of starts at the screenshot.
I haven't found any scenario setting that would cause this (apart from that a bot must be present). It is inconsistent in that around one in four or five games starts well and proceeds into the game.
I've tried slowing down client connections but this had no effect (and besides, it seems that the bot is connected and has clicked done, so that's not an issue).

![image](https://user-images.githubusercontent.com/17069663/114297905-af8cdd00-9ab3-11eb-9881-384f2bad4d57.png)

**Comment by HoneySkull** [comment]
I've seen this too with the latest 0.49.1-Snapshot on windows running from Eclipse or Gradle command line.    I've attached the logs.  This was starting the IceStorm.mms scenario.   Wondering if it's because the unit list is out of whack or if it's because it can't find certain unit files.

[megameklog.txt](https://github.com/MegaMek/megamek/files/6488381/megameklog.txt)

**Comment by HammerGS** [comment]
Don't recall seeing this one before:

```
17:43:36,423 ERROR [megamek.common.GameReports] {AWT-EventQueue-0} 
get(), line 66 : ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
java.lang.RuntimeException: ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
	at megamek.common.GameReports.get(GameReports.java:64)
	at megamek.common.Game.getReports(Game.java:2762)
	at megamek.client.Client.handlePacket(Client.java:1539)
	at megamek.client.Client$1$2.run(Client.java:170)
```

**Comment by HoneySkull** [comment]
Yeah, that's interesting, because this "freezes" before the deployment phase.  

When on the phase report screen I do a save game.  I shutdown megamek, and then load from the save game.  by loading the save game, I'm able to continue to the deployment phase and continue the game.

**Comment by HoneySkull** [comment]
I tried loading the same scenario in the stable 0.48.  The game gets to the deployment phase but I had to 'ReplacePlayer' for the bot even though the bot was selected for the scenario start.  

I also see the following error in the 0.48 stable load:

```
18:18:54,650 ERROR [megamek.common.GameReports] {AWT-EventQueue-0} 
get(), line 66 : ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
java.lang.RuntimeException: ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
	at megamek.common.GameReports.get(GameReports.java:64)
	at megamek.common.Game.getReports(Game.java:2758)
	at megamek.client.Client.handlePacket(Client.java:1411)
	at megamek.client.Client$1$2.run(Client.java:193)

```

**Comment by HoneySkull** [comment]
![image](https://user-images.githubusercontent.com/83041327/118381089-ef604c00-b5ac-11eb-813c-158e1b5c593d.png)

Also tried to load the scenario from a clean nightly build from May 5th.  Again - didn't get to the deployment phase, and it looks like the bot and I are flagged as done - but I did not hit the 'Done' button yet.  When I click the 'Done' button, it then becomes grayed out.

**Comment by HoneySkull** [comment]
This looks like a race condition.  In 0.49.x there are multiple threads attempting to simultaneously change the game phase during the launch of the scenario.  While in 0.48 stable, it appears that only one thread is attempting to change the game phase at a time.  If I set a breakpoint in Server.java `endCurrentPhase()` I can see/control which thread 'wins' and either get to the deployment phase or stuck on the initiative / report phase.

**Comment by Windchild292** [comment]
Is this fixed in latest?

**Comment by HoneySkull** [comment]
No, this is still broken as of May 17th latest. (ab24f5d).   This root cause of this issue, could also be the root cause of other issues related to missing phase reports or phases.   I find that this also causes auto save to often be triggered multiple times simultaneously that could cause corrupt save games.

**Comment by HoneySkull** [comment]
I suspect this issue is the root cause of #2859.  This is just easier to reproduce when starting a scenario because of the way that server starts up without the lobby.

**Comment by Windchild292** [comment]
My apologies, confused the type of scenario.
