### ISSUE TITLE
[0.50.0-SNAPSHOT] Unable to load savegames. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek#5756]
### Environment
02:51:53,126 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:142) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-07-18T01:16:03.132246751
    Today: 2024-07-20
    Origin Project: MegaMek
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 2 GB
    MM Code Revision: Unknown
    MML Code Revision: Unknown
    MHQ Code Revision: Unknown

### Description
Cannot load any savegames in client, including those provided by others.

![image](https://github.com/user-attachments/assets/2d235a62-2841-41b9-b870-e395f77fa8a8) 

### Files
[megamek.log](https://github.com/user-attachments/files/16318114/megamek.log)

**Comment by repligator** [comment]
If you save a game yourself, can you load that?

**Comment by Tzahr** [comment]
Of course. 
First thing I did was check if I could load any of my own autosaves, but they all return the same error. 

[quicksave.sav.gz](https://github.com/user-attachments/files/16321738/quicksave.sav.gz)

**Comment by repligator** [comment]
Well, good news is I can't load the save either.

**Comment by HammerGS** [comment]
Any chance this was done between commits or nightlies? That could cause the issue.

**Comment by Tzahr** [comment]
I had savegame loading issues in a previous Nightly - it'd load, but only to the lobby and lose all round progress, so the underway autosaves and quicksaves were useless. It was on my list to investigate further, and then I switched to a more recent build and MegaMek saves are not loading at all. 

I was given a test save to load for the Aerospace bombing bug when we were trying to replicate that, and that wasn't/isn't loading either.

**Comment by HammerGS** [comment]
You have a Thunderbolt Mek (Any) by chance?

**Comment by repligator** [comment]
> quicksave.sav.gz

This save _should_ fail. It makes perfect sense that it is failing. The very first entity never actually ends.
The fact that other saves, that are formatted correctly, are also failing for you is puzzling. They are even throwing the same error.
`XML document structures must start and end within the same entity.`
Despite the fact that I can open the save file in a text editor and clearly see that it does, in fact, start and end with the same entity.

**Comment by Tzahr** [comment]
> You have a Thunderbolt Mek (Any) by chance?

I do in my campaign save, but also non-HQ games without TBolts are not loading.

**Comment by Tzahr** [comment]
Updated to the latest Nightly. 
Same issue still. 

Failure to load on the following files: 
[Round-2-autosave_2024-07-21_14-30-53.sav.gz](https://github.com/user-attachments/files/16324447/Round-2-autosave_2024-07-21_14-30-53.sav.gz)
[PrincessArosospaceTest.sav.gz](https://github.com/user-attachments/files/16324449/PrincessArosospaceTest.sav.gz)

Log:
[megamek.log](https://github.com/user-attachments/files/16324451/megamek.log)

**Comment by repligator** [comment]
Could this be a Java version issue?

**Comment by rjhancock** [comment]
The save files are corrupted. They are incomplete XML files.

![Screenshot 2024-07-21 at 08 02 23](https://github.com/user-attachments/assets/f7
![Screenshot 2024-07-21 at 08 02 19](https://github.com/user-attachments/assets/f193209a-bba4-49d6-abc3-7d5286431127)
47171a-a090-437b-8402-51771ba4e51e)

**Comment by rjhancock** [comment]
I'd suggest trying with a more recent nightly and start with a fresh save with that client.

**Comment by repligator** [comment]
I was running MM via MHQ last night, and made some saves (auto and manual) while it was close to running out of memory. They both end incorrectly in the middle of lines (the last line doesn't end with `>`). However, even is these display the same symptoms as Tzahr's saves, it doesn't explain why known good saves won't load, and throw the same error as bad saves. It also seems unlikely that Tzarhr is OOM constantly. I don't see any changes to XML reading and writing in the last several months (although I could just be missing something). This combined with the fact that there seems to be saving _and_ loading issues makes me suspect an issue with Java versions.

[Round-11-autosave_2024-07-20_17-21-12.sav.gz](https://github.com/user-attachments/files/16324535/Round-11-autosave_2024-07-20_17-21-12.sav.gz)
[testsave.sav.gz](https://github.com/user-attachments/files/16324536/testsave.sav.gz)

**Comment by Tzahr** [comment]
This is the most recent Nightly.
I am creating fresh games, only importing my settings, and the savegames they generate are corrupt. 
Essentially, I start up an MM lobby, create a game, play a few rounds, and then look at the autosave. It fails to load those. 
At this point I'm not even trying to load in autosaves from previous versions.  

Incidentally: this save was given to me by someone else for a test, also fails to load. 
The log for this one is giving different errors that might be more useful.

[megamek.log](https://github.com/user-attachments/files/16324547/megamek.log)
[princess_bomb_test.sav.gz](https://github.com/user-attachments/files/16324541/princess_bomb_test.sav.gz)

----

As a control group, I also ran a completely fresh install of the same Nightly, no alterations at all. Just unzipped it, opened MM, played like 3-4 rounds and made a quicksave.
Didn't load.

Save and logs attached:

[megamek.log](https://github.com/user-attachments/files/16324576/megamek.log)
[quicksave.sav.gz](https://github.com/user-attachments/files/16324575/quicksave.sav.gz)

**Comment by kuronekochomusuke** [comment]
megamek saves are not backwards compatible.  any change to the object structure can cause saves created on older nightly versions to no longer work.

for any saves that are from the same night version, we need the log file from when the save is created to see if there is an error causing the curruption.

**Comment by repligator** [comment]
> As a control group, I also ran a completely fresh install of the same Nightly, no alterations at all. Just unzipped it, opened MM, played like 3-4 rounds and made a quicksave.
> Didn't load.

This looks promising.

`15:18:12,988 ERROR [megamek.server.GameManagerSaveHelper] {Packet Pump}
megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:70) - Unable to save file: savegames\autosave.sav
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null`

**Comment by kuronekochomusuke** [comment]
15:18:12,988 ERROR [megamek.server.GameManagerSaveHelper] {Packet Pump}
megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:70) - Unable to save file: savegames\autosave.sav
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:96)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:80)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1303)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1292)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1265)
	at megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:68)
	at megamek.server.AbstractGameManager.saveGame(AbstractGameManager.java:182)
	at megamek.server.AbstractGameManager.autoSave(AbstractGameManager.java:177)
	at megamek.server.TWPhasePreparationManager.managePhase(TWPhasePreparationManager.java:217)
	at megamek.server.GameManager.prepareForCurrentPhase(GameManager.java:1673)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:88)
	at megamek.server.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:72)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:1830)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:91)
	at megamek.server.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:53)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:1830)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:1971)
	at megamek.server.GameManager.executeCurrentPhase(GameManager.java:1711)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:95)
	at megamek.server.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:44)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:1830)
	at megamek.server.GameManager.checkReady(GameManager.java:1228)
	at megamek.server.AbstractGameManager.handlePacket(AbstractGameManager.java:58)
	at megamek.server.GameManager.handlePacket(GameManager.java:570)
	at megamek.server.Server.handle(Server.java:1280)
	at megamek.server.Server$PacketPump.run(Server.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by rjhancock** [comment]
Have a pending fix. Doing some clean up now. This bug is related to the removal of SerialKiller.

**Comment by rjhancock** [comment]
Please download the latest nightly and confirm this is fixed for you.

**Comment by Tzahr** [comment]
Downloaded latest Nightly, tested again, issue persists, same symptoms. 

Loaded it up clean, only change I did was to enable Sentry. Everything else is just out of the box. 
Started a new game of MegaMek vs. Princess, ran two-three rounds.
Keeps pinging a message in chat saying it can't autosave. Quicksave works, but neither load. 

Log file seems to suggest same XML corruption as before. 
Generated saves and logs attached. 


[Round-0-autosave_2024-07-22_07-11-49.sav.gz](https://github.com/user-attachments/files/16328162/Round-0-autosave_2024-07-22_07-11-49.sav.gz)
[quicksave.sav.gz](https://github.com/user-attachments/files/16328163/quicksave.sav.gz)
[autosave.sav.gz](https://github.com/user-attachments/files/16328164/autosave.sav.gz)
[Round-2-autosave_2024-07-22_07-12-09.sav.gz](https://github.com/user-attachments/files/16328165/Round-2-autosave_2024-07-22_07-12-09.sav.gz)
[Round-1-autosave_2024-07-22_07-11-55.sav.gz](https://github.com/user-attachments/files/16328166/Round-1-autosave_2024-07-22_07-11-55.sav.gz)

[megamek.log](https://github.com/user-attachments/files/16328173/megamek.log)

**Comment by rjhancock** [comment]
HOW are you running MegaMek? EXE? BAT? JAR? CLI?

**Comment by Tzahr** [comment]
Aha! 

I was running it through the MegaMek.exe. 
I ran it again through the JAR file, and the issue resolved. Autosaves function fine, quicksave functions fine, both load without issue. 

If I was meant to be running it through the JAR file all along, I apologise for my oversight, I assumed the .exe would function more or less identically. 

[quicksave.sav.gz](https://github.com/user-attachments/files/16328342/quicksave.sav.gz)
[megamek.log](https://github.com/user-attachments/files/16328340/megamek.log)
[autosave.sav.gz](https://github.com/user-attachments/files/16328343/autosave.sav.gz)

**Comment by rjhancock** [comment]
No, just trying to track the actual error. The EXEs are there as a convenience for Windows users but otherwise aren't needed when Java is setup correctly.

And that confirmed my suspicions. 

Put this in the MegaMek.l4j.ini file and try again.

```
-Xmx2048m
--add-opens
java.base/java.util=ALL-UNNAMED
--add-opens
java.base/java.util.concurrent=ALL-UNNAMED
-Dsun.awt.disablegrab=true
```

**Comment by Tzahr** [comment]
Put that in, ran the game through the .exe. 
Issue appears resolved!

Logs & saves in case they're still useful:
[autosave.sav.gz](https://github.com/user-attachments/files/16333097/autosave.sav.gz)
[quicksave.sav.gz](https://github.com/user-attachments/files/16333098/quicksave.sav.gz)
[megamek.log](https://github.com/user-attachments/files/16333093/megamek.log)

**Comment by Sleet01** [comment]
Closing as there appears to be a work-around or actual fix.  Thanks to everyone for their assistance and diligence!
